apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: younis606/vote:latest
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          value: redis-master.vote.svc.cluster.local
        - name: REDIS_API_KEY
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_API_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: vote-app-secret
              key: JWT_SECRET
