apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  namespace: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
        - name: vote
          image: younis606/vote:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis-master.vote.svc.cluster.local"
