apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-postgres
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-postgres
  template:
    metadata:
      labels:
        app: voting-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: voting-app-dev
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-app-dev
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: voting-app-dev
                  key: postgres_db
