apiVersion: v1
kind: Service
metadata:
  name: voting-postgres
  namespace: vote
spec:
  type: ClusterIP
  selector:
    app: voting-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
