apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
        - name: voting-app
          image: youniss606/voting-app:latest
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: "voting-postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: REDIS_HOST
              value: "voting-redis"
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vote-dev-secrets
                  key: jwt_secret
