apiVersion: v1
kind: Service
metadata:
  name: voting-app
  namespace: vote
spec:
  type: ClusterIP
  selector:
    app: voting-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
