apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-redis
  template:
    metadata:
      labels:
        app: voting-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-app
                  key: redis_password
